### ISSUE TITLE
Bad Import

### ISSUE THREAD

**Issue by TobiahRex** [toomuchdesign/react-minimal-pie-chart#1]
`import PieChart from 'react-minimal-pie-chart' `

Throws error: Unable to resolve path to module 'react-minimal-pie-chart'.

**Comment by toomuchdesign** [comment]
Thanks @TobiahRex, [v0.0.1](https://github.com/toomuchdesign/react-minimal-pie-chart/releases/tag/v0.0.1) should fix it.
