### ISSUE TITLE
Pie Chart parts are losing proportions after animation

### ISSUE THREAD

**Issue by razked** [toomuchdesign/react-minimal-pie-chart#112]
### Do you want to request a _feature_ or report a _bug_?
I believe this is a bug
...

### What is the current behaviour?
when animation prop is set to TRUE the first Pie Chart part is losing his propotion and his not Straight as without animation.
I checked this on both Chrome and Firefox.

also, I have seen this behaviour in the documentation.
...

### What is the expected behaviour?
Straight-line as without the animation when animation prop is set to TRUE
...

### Steps to Reproduce the Problem

1. ...
![with animation](https://user-images.githubusercontent.com/39411034/69922827-3c7b5b80-14a8-11ea-8f18-965b3f3616d8.PNG)

![no-animation](https://user-images.githubusercontent.com/39411034/69922829-41400f80-14a8-11ea-8271-5ac9cb665d2d.PNG)

2. ...
3. ...

### Specifications

- Version: Latest one
- Platform:
- Subsystem:

**Comment by toomuchdesign** [comment]
Hi @razked,
thanks for raising the issue. In which OS have you encountered this problem?

**Comment by razked** [comment]
Hey !

Win 2010

**Comment by toomuchdesign** [comment]
Merged into #129
