### ISSUE TITLE
Can't get percentage for values working

### ISSUE THREAD

**Issue by rikoz** [toomuchdesign/react-minimal-pie-chart#115]
Please what exactly do I pass into label as prop to get values display as percentage.

**Comment by toomuchdesign** [comment]
Hi @rikoz,
please take a look at the demo source code:
https://github.com/toomuchdesign/react-minimal-pie-chart/blob/58aa79e9b1d45ac0828b464e5a50d27805ce6af3/stories/index.js#L119
