### ISSUE TITLE
Piechart is 300px by default, how can I make it smaller ?

### ISSUE THREAD

**Issue by stilllife00** [toomuchdesign/react-minimal-pie-chart#12]
### Do you want to request a *feature* or report a *bug*?
Info request

### What is the current behaviour?
The piechart has a default size of 300px and I cannot make it smaller

### What is the expected behaviour?
A smaller piechart. I couldn't find any setting to reduce it

### Steps to Reproduce the Problem

  1. Make a piechart
  2. The piechart is too big
  3. Sadness

**Comment by toomuchdesign** [comment]
Hi @stilllife00,
the chart should fit its wrapping element size. Can you provide a more detailed example?

Cheers!

**Comment by stilllife00** [comment]
I managed to reproduce the problem in a sandbox: https://codesandbox.io/s/8lrlxq07nl

Basically setting the wrapping element's `width` works but setting the `height` doesn't. You can see the blue piechart overflowing is parent. 

I guess this is not the desired behaviour ? It is not a big deal but this forces to set the width explicitly when the natural height of the parent should be enough.
