### ISSUE TITLE
Link in README.md to source code of demo is broken

### ISSUE THREAD

**Issue by Raulif** [toomuchdesign/react-minimal-pie-chart#15]
### Do you want to request a _feature_ or report a _bug_?
bug
...

### What is the current behaviour?
Link in README.md to source code of demo is broken.
...

### What is the expected behaviour?
Link should go to source code file page (github.com/...../stories/index.js);
...

### Steps to Reproduce the Problem

1. in README.md file, change current link stored in variable [demo-interaction-source] from:
"https://github.com/toomuchdesign/react-minimal-pie-chart/blob/v3.1.0/stories/index.js#L25" 
to:
"https://github.com/toomuchdesign/react-minimal-pie-chart/blob/master/stories/index.js".

### Specifications

- Version:
- Platform:
- Subsystem:

Thanks for this cool component!!

**Comment by toomuchdesign** [comment]
Hi @Raulif, good point! It will be fixed as soon as I release **v3.1.0**.
I usually avoid creating links pointing to branches since they break so often!

Cheers!

**Comment by toomuchdesign** [comment]
Fixed! :)
