### ISSUE TITLE
labelPosition is broken in 7.3.0

### ISSUE THREAD

**Issue by majelbstoat** [toomuchdesign/react-minimal-pie-chart#155]
### Do you want to request a _feature_ or report a _bug_?

report a _bug_
...

### What is the current behaviour?

Run the default labels example and observe the labels are all collapsed in the middle of the image.

...

### What is the expected behaviour?

The labels appear in the correctly specified position.

...

### Steps to Reproduce the Problem

1. Copy the props defined the default labels story.
2. Observe all the labels collapsed on top of each other.

The issue doesn't occur in 7.2.0

### Specifications

- Version: 7.3.0

**Comment by toomuchdesign** [comment]
Hi @majelbstoat,
thanks for reporting! Something went wrong in the last release. :) There's a PR to address the issue and second one will come soon. Feel free to take a look and leave comments.

Greetings!

**Comment by toomuchdesign** [comment]
Hopefully fixed by v7.3.1.
