### ISSUE TITLE
Using string instead of a numeric for slice labels

### ISSUE THREAD

**Issue by db-baron** [toomuchdesign/react-minimal-pie-chart#166]
How can a string be used for a label text? I was expecting "Placeholder" to be displayed in all slices using the code below.
```
               <ReactMinimalPieChart
                  cx={50}
                  cy={40}
                  data={this.state.piechart_data}
                  label={"Placeholder"}
                  labelPosition={72}
                  labelStyle={{
                    fill: 'white',
                    fontFamily: 'Arial',
                    fontSize: '2.5px'
                  }}
```

**Comment by toomuchdesign** [comment]
Hi @db-baron,
`label` props [expects a function](https://github.com/toomuchdesign/react-minimal-pie-chart#custom-labels-with-label-render-prop) returning the value or element to be rendered as label.

In your case:
```
label={() => "Placeholder"}
```
