### ISSUE TITLE
Import library issue. Standard way to import this "import  PieChart  from 'react-minimal-pie-chart';" or "import  { PieChart }  from 'react-minimal-pie-chart';" 

### ISSUE THREAD

**Issue by Elaiya** [toomuchdesign/react-minimal-pie-chart#174]
### Do you want to request a _feature_ or report a _bug_?

...

### What is the current behaviour?

...

### What is the expected behaviour?

...

### Steps to Reproduce the Problem

1. ...
2. ...
3. ...

### Specifications

- Version: 8.0.1
- Platform:
- Subsystem:

**Comment by toomuchdesign** [comment]
Chart component is exposed as a named export and is supposed to be imported like:

```js
import { PieChart } from 'react-minimal-pie-chart'
```
