### ISSUE TITLE
Chartboost delegate issue react native

### ISSUE THREAD

**Issue by dangaj** [toomuchdesign/react-minimal-pie-chart#18]
I have integrated chartboost in my react native app. I am facing an issue. When i go to my screen where i have implemented chartboost delegate and came back to previous screen and then go again to that screen delegated methods will call 2 times and it keeps on increasing as i go back and forth. Result is i get multiple callbacks in rewarded video. Can anyone help how to disable chartboost on ComponentwillUnmount? (https://gyazo.com/2a3628505aed02abcf08f8999ef8a363) Here is my code (https://gyazo.com/506b50259b475302e991155e0e91efc4).

**Comment by toomuchdesign** [comment]
Hi @dangaj,
maybe this belongs to another repo?
