### ISSUE TITLE
not showing data labels

### ISSUE THREAD

**Issue by JasonParra** [toomuchdesign/react-minimal-pie-chart#187]
### Do you want to request a _feature_ or report a _bug_?
bug

### What is the current behaviour?
not showing data labels
`<PieChart
  data={[
    { title: 'One', value: 10, color: '#E38627' },
    { title: 'Two', value: 15, color: '#C13C37' },
    { title: 'Three', value: 20, color: '#6A2135' },
  ]}
/>;`
https://i.imgur.com/RvnjwzU.png

### What is the expected behaviour?
https://imgur.com/V3cYNEP

### Steps to Reproduce the Problem
1. npm install react-minimal-pie-chart
2. run example code
3. ...

### How i partially solved
Adding
`    label={(props) => { return props.dataEntry.title;}}`

Example
`  <PieChart
    label={(props) => { return props.dataEntry.title;}}
    data={[{ title: "One", value: 10, color: "#E38627" },
           { title: "Two", value: 15, color: "#C13C37" },
           { title: "Three", value: 20, color: "#6A2135" },
    ]}
    />`

### Specifications

- Version:  "react": "^16.13.1",
- Platform: windows 10
- Subsystem: none

**Comment by toomuchdesign** [comment]
Hi @JasonParra,
that's the way to go. `label` prop expects a function receiving `labelRenderProps` as argument and returning one of the following:

- number
- string
- React.ReactElement
- undefined
- null

https://github.com/toomuchdesign/react-minimal-pie-chart#custom-labels-with-label-render-prop

**Comment by floraCodes** [comment]
I'm trying to return a ReactElement but it's not showing. I mean, it's being rendered inside the svg as an element of dimensions 0x0. 

Not sure whats going on here... Any ideas?
![Screen Shot 2020-12-14 at 4 37 11 pm](https://user-images.githubusercontent.com/40923958/102044314-ab64f180-3e2a-11eb-94f8-9bf724f066bc.png)

**Comment by toomuchdesign** [comment]
Hi @JasonParra,
since react-minimal-pie-chart renders as SVG, labels have to render [SVG elements](https://developer.mozilla.org/en-US/docs/Web/SVG/Element). See [default label implementation](https://github.com/toomuchdesign/react-minimal-pie-chart/blob/master/src/Label.tsx).

In your case, `label` function might more simply return a number or string.

**Comment by floraCodes** [comment]
@toomuchdesign thanks for the reply, I was wondering if I can render a react element so I can add functionality inside the label...

**Comment by toomuchdesign** [comment]
Every element is a React element. :) What matters is that the element provided as `label` prop makes use of SVG elements only.
