### ISSUE TITLE
Text strings must be rendered within <Text> when imported the default example

### ISSUE THREAD

**Issue by prashantbasnet94** [toomuchdesign/react-minimal-pie-chart#193]
### Do you want to request a _feature_ or report a _bug_?

...

### What is the current behaviour?

...

### What is the expected behaviour?

...

### Steps to Reproduce the Problem

1. ...
2. ...
3. ...

### Specifications

- Version:
- Platform:
- Subsystem:

**Comment by toomuchdesign** [comment]
In case reopen with more info.
