### ISSUE TITLE
View config not found for name path

### ISSUE THREAD

**Issue by balsikandar** [toomuchdesign/react-minimal-pie-chart#20]
### Do you want to request a _feature_ or report a _bug_?
Report a bug
...

### What is the current behaviour?
Getting issue in rendering PieChart. After deep debugging and [stackoverflow](https://stackoverflow.com/questions/46750477/react-native-invariant-violation-view-config) it seems **path** component in **ReactMinimalPieChartPath** should be capitalised. Please look into this. 

`Invariant Violation: Invariant Violation: Invariant Violation: View config not found for name path

This error is located at:
    in path (created by ReactMinimalPieChartPath)
    in ReactMinimalPieChartPath (created by ReactMinimalPieChart)
    in svg (created by ReactMinimalPieChart)
    in div (created by ReactMinimalPieChart)
    in ReactMinimalPieChart (at StandardScreen.js:30)
    in RCTView (at View.js:60)
    in View (at StandardScreen.js:17)
    in StandardScreen (at SceneView.js:9)
    in SceneView (at createTabNavigator.js:38)
    in RCTView (at View.js:60)
    in View (created by ViewPagerAndroid)
    in AndroidViewPager (at ViewPagerAndroid.android.js:236)
    in ViewPagerAndroid (at PagerAndroid.js:148)
    in PagerAndroid (at TabView.js:60)
    in RCTView (at View.js:60)
    in View (at TabView.js:191)
    in RCTView (at View.js:60)
    in View (at TabView.js:189)
    in TabView (at createMaterialTopTabNavigator.js:246)
    in MaterialTabView (at createTabNavigator.js:177)
    in NavigationView (at createNavigator.js:62)
    in Navigator (at createAppContainer.js:383)
    in NavigationContainer (at EmiCalculatorTabScreen.js:64)
    in WrapperScreen (created by Connect(WrapperScreen))
    in Connect(WrapperScreen) (at EmiCalculatorBaseContainer.js:51)
    in EmiCalculatorBaseContainer (created by Connect(EmiCalculatorBaseContainer))
    in Connect(EmiCalculatorBaseContainer) (at EmiCalculatorEntryPoint.js:74)
    in Provider (at EmiCalculatorEntryPoint.js:73)
    in EmiCalculatorEntryPoint (at SceneView.js:9)
    in SceneView (at StackViewLayout.js:763)
    in RCTView (at View.js:60)
    in View (at StackViewLayout.js:762)
    in RCTView (at View.js:60)
    in View (at StackViewLayout.js:761)
    in RCTView (at View.js:60)
    in View (at createAnimatedComponent.js:154)`
...

### What is the expected behaviour?
It should be rendered properly. I believe this **path** needs to be capitalised. 
...

### Steps to Reproduce the Problem

1. I just added this library and this code
`import PieChart from 'react-minimal-pie-chart';

<PieChart
  data={[
    { title: 'One', value: 10, color: '#E38627' },
    { title: 'Two', value: 15, color: '#C13C37' },
    { title: 'Three', value: 20, color: '#6A2135' },
  ]}
/>;`

### Specifications

- react-minimal-pie-chart : ^3.3.0
- react-native: 0.55.4

**Comment by toomuchdesign** [comment]
Hi @balsikandar,
this library was written for the web, therefore the mentioned `path` element refers to the browser native [SVG path element](https://www.w3schools.com/graphics/svg_path.asp).

Do you see any way to make this library somehow compatible with react native targets?

Greetings!

**Comment by balsikandar** [comment]
Thanks for the clarification. I end up doing same with SVG and ART so didn't get any chance to make it work in react native. I'll give it another shot soon. 

Thanks

**Comment by PurnimaNaik** [comment]
Any updates on this?
