### ISSUE TITLE
How to show percentage ?

### ISSUE THREAD

**Issue by torikraju** [toomuchdesign/react-minimal-pie-chart#21]
how to show percentage like 
![image](https://user-images.githubusercontent.com/22712892/50632585-8a26d580-0f72-11e9-9c1b-0263257deb1b.png)

**Comment by toomuchdesign** [comment]
Hi @torikraju,
this feature is currently not supported.

I'm trying to keep this component very basic and straightforward, but I'm open to consider any idea to integrate segment value rendering in the chart.

**Comment by jmrapp1** [comment]
The component becomes kind of useless for not supporting a feature like a basic percentage display. A Pie Chart is not interpretable without a display of some sort.

**Comment by toomuchdesign** [comment]
Hi @jmrapp1,
thanks for the constructive feedback. The feature is coming soon.

**Comment by jmrapp1** [comment]
Awesome to hear!

**Comment by toomuchdesign** [comment]
Shipped with [v3.5.0](https://github.com/toomuchdesign/react-minimal-pie-chart/releases/tag/v3.5.0).
