### ISSUE TITLE
Custom SVG label is rendered on same position

### ISSUE THREAD

**Issue by Q8root** [toomuchdesign/react-minimal-pie-chart#216]
### What is the current behaviour?
When trying to create custom svg label, all labels are rendering on same position
```
const Element = (props) => {
  return (
    <text
      dominant-baseline="central"
      x="50"
      y="50"
      dx="19.151111077974452"
      dy="16.06969024216348"
      text-anchor="middle"
      style={{ fontSize: "10px" }}
    >
      <tspan x="50" dy="1.2em">
        {`${Math.round(props.percentage)} %`}
      </tspan>
      <tspan x="0" dy="1.2em">
        {props.title}
      </tspan>
    </text>
  );
};
<PieChart
              data={[
                { title: "Excellent", value: 10, color: "#8dcd81" },
                { title: "Good", value: 15, color: "#eefa6b" },
                { title: "Weak", value: 20, color: "#FF6382" },
              ]}
              label={({ dataEntry }) => <Element {...dataEntry} />}
            />
```
http://snpy.in/GbMYIf

...

### What is the expected behaviour?
http://snpy.in/sJbYj2
...

**Comment by toomuchdesign** [comment]
It seems that labels are rendered with the same `x`, `y`, `dx`, `dy` values. You're supposed to get/adapt their relevant values from `props`.

**Comment by Q8root** [comment]
> It seems that labels are rendered with the same `x`, `y`, `dx`, `dy` values. You're supposed to get/adapt their relevant values from `props`.

Can you please explain, how can i do that ?

**Comment by toomuchdesign** [comment]
`label` render prop accept a function with the signature [described here](https://github.com/toomuchdesign/react-minimal-pie-chart#custom-labels-with-label-render-prop). You might pass `x`, `y`, `dx`, `dy` values down to the custom svg element.
