### ISSUE TITLE
Gradients for pie chart segments

### ISSUE THREAD

**Issue by nehoraigold** [toomuchdesign/react-minimal-pie-chart#22]
### Do you want to request a _feature_ or report a _bug_?

Requesting a feature.

### What is the current behaviour?

Currently, gradients are not supported. That is, segments in the pie chart can only be of a single color.

### What is the expected behaviour?

I know that you're trying to keep things simple (it is minimal after all), but even the possibility of injecting defs into the SVG via another property on the PieChart component to define our own gradients (and then reference them with the color property) would be awesome. Just an idea!

**Comment by toomuchdesign** [comment]
Hi @nehoraigold,
I'd definitely introduce this feature. Do you have any suggestion about what a good API might look like?

**Comment by nehoraigold** [comment]
Hi @toomuchdesign,

I think having another property on the component that could accept JSX code and inject it within the SVG element would enable this. It's probably a fairly simple implementation and could enable users to customize the SVGs in ways that allow for more than just gradients.

See the image below for how this could work (note the "inject" property as well as how the "color" property in the data references the gradient ID):

![2019-02-09_1543](https://user-images.githubusercontent.com/44398222/52521622-8cbbcf80-2c82-11e9-9d4c-7ded75fea846.png)

I was able to do this by passing the defs component to the "children" property and changing the location where this.props.children is rendered in the package, but this is obviously not ideal.

Thanks, and I hope this helps!

**Comment by toomuchdesign** [comment]
Hey @nehoraigold,
Here is a very quick draft the feature: #23.

I'm not sure what an expressive name for our new `inject` property could be...

I also thought the `inject` property could be more powerful if provided as a function. How do you see it?

Please let me have any feedback,
Greetings!

**Comment by nehoraigold** [comment]
Looks good! If `inject` isn't expressive enough, maybe `injectSvg` or `injectToSvg` could be good alternatives.

**Comment by toomuchdesign** [comment]
Seems we're done here. Thank's @nehoraigold!

`injectSvg` added in [v3.4.0](https://github.com/toomuchdesign/react-minimal-pie-chart/releases/tag/v3.4.0).

**Comment by ddennis** [comment]
I looking for an example of using either the injectSvg or children for rendering each segment with a gradient.
i can't get this to work:

```
 <PieChart
            lineWidth={30}
            segmentsStyle={(itemIndex) => {
              return {}
            }}
            children={
              <defs>
                <linearGradient id={'grad2'} x1={'0%'} y={'0%'} x2={'0%'} y2={'100%'}>
                  <stop offset={'0%'} stopColor={'rgb(226, 52, 137)'} />
                  <stop offset={'100%'} stopColor={'rgb(168, 49, 213)'} />
                </linearGradient>
              </defs>
            }
            data={[
              { title: 'One', value: 10 },
              { title: 'Two', value: 15, color: '#C13C37' },
              { title: 'Three', value: 20, color: '#6A2135' }
            ]}
          />
```

Any help would be much appreciated.
/Dennis

**Comment by toomuchdesign** [comment]
Hi @ddennis,
have you tried following [this example](https://github.com/toomuchdesign/react-minimal-pie-chart/blob/9ee16f7b398113dcd26ddba45df2c506a7456afe/stories/index.tsx#L154)?

**Comment by ddennis** [comment]
@toomuchdesign thanks alot for the quick response. Sorry i didn't see the storybook example.
Are there a clever way of getting the angle of each segment, in order to rotate the `gradientTransform="rotate(0)"`
Thanks again.
/Dennis

**Comment by toomuchdesign** [comment]
If I'm not mistaken, the only place where segments angle are exposed are in [`label` render prop](https://github.com/toomuchdesign/react-minimal-pie-chart#custom-labels-with-label-render-prop).

**Comment by ddennis** [comment]
:+1:  Fantastic. Thanks for your time.
