### ISSUE TITLE
Edges are getting cut on hover, when we render Doughnut chart

### ISSUE THREAD

**Issue by saiyamjain143** [toomuchdesign/react-minimal-pie-chart#229]
### Do you want to request a _feature_ or report a _bug_?
Bug
...

### What is the current behaviour?
When we hover on any of the segment, and apply segment shift, then the segment is getting cut.
![image](https://user-images.githubusercontent.com/31028359/128635681-9ad1bb9e-e359-4e82-b3e9-076e1d356d74.png)

...

### What is the expected behaviour?
- On hover, segments should not be cut
...

### Steps to Reproduce the Problem
1. Create a doughnut chart
2. Add `segmentsShift` to some value on mouse over

`<PieChart
        data={data}
        className={styles.doughnut}
        segmentsStyle={{
          transition: "stroke .3s",
          cursor: "pointer",
          margin: "0.5rem",
        }}
        segmentsShift={(index) => (index === selected ? 7 : 0)}
        onMouseOver={(_, index) => {
          setSelected(index === selected ? undefined : index);
        }}
        onMouseOut={(_, index) => {
          setSelected(index === selected ? undefined : index);
        }}
        lineWidth={20}
        paddingAngle={4}
      />`

### Specifications

- Version: 8.2.0

**Comment by mledwards** [comment]
Assuming you closed this because you found the `radius` and `viewBox` options?
