### ISSUE TITLE
Hide tooltip

### ISSUE THREAD

**Issue by saiyamjain143** [toomuchdesign/react-minimal-pie-chart#231]
### Do you want to request a _feature_ or report a _bug_?
_feature_ : Hide tooltip

### What is the current behaviour?
Tooltip doesn't hide, and no props to hide it

### What is the expected behaviour?
There should be a prop `hideTooltip`, if user doesn't want to render tooltip

**Comment by bryantobing12** [comment]
so there's no option to remove default tooltip ?

**Comment by toomuchdesign** [comment]
Yep, you can see it here:
https://github.com/toomuchdesign/react-minimal-pie-chart/blob/master/src/Path.tsx#L95
