### ISSUE TITLE
Feature OnMouseOver or specific classname when it is selected

### ISSUE THREAD

**Issue by c0ncentus** [toomuchdesign/react-minimal-pie-chart#238]
### What is the current behaviour?
poor UX when bar is selected (only shift or color change)

### What is the expected behaviour?
Have possibilities to make border brightness when is selected.

### Some Other possibilities
Make available some specific classname when it is selected . So we can make style on our own.

**Comment by toomuchdesign** [comment]
Hi @c0ncentus,
the library doesn't expose class names by design. Specific segments can be styled through `segmentsStyle` prop by providing a function.

**Comment by c0ncentus** [comment]
i try   
```
segmentsStyle ={()=>{return {boxShadow: "inset 0px 0px 60px whitesmoke, inset 20px 0px 80px #f0f, inset -20px 0px 80px #0ff, inset 20px 0px 300px #f0f, inset -20px 0px 300px #0ff, 0px 0px 50px #fff, -10px 0px 80px #f0f, 10px 0px 80px #0ff"} }
``` 


and
```
segmentsStyle ={()=>{return {boders: "20px crimson solid"} }
``` 

I test to add direcly on <path> element and didn't work too : /
