### ISSUE TITLE
How to style labels ?

### ISSUE THREAD

**Issue by goupilAnthony** [toomuchdesign/react-minimal-pie-chart#241]
I'm trying to integrate a pie chart in my NextJS app.
The size of the label is really huge, I want to reduce it but I don't understand why it's not working like I think

Here is the code
```js
<PieChart
    data={[
	    { title: "One", value: 10, color: "#E38627" },
	    { title: "Two", value: 15, color: "#C13C37" },
	    { title: "Three", value: 20, color: "#6A2135" },
    ]}
    label={({ dataEntry }) => dataEntry.title}
    labelStyle={{ fontSize: "1rem" }}
/>
```
and it renders that:
![image](https://user-images.githubusercontent.com/36542885/143044455-b873203b-2668-4631-812a-2c0979c58a14.png)
as you can see the color isn't white and the font size isn't 1rem

**Comment by toomuchdesign** [comment]
Hi @goupilAnthony,
wrong `labelStyle` prop signature.

**Comment by goupilAnthony** [comment]
> Hi @goupilAnthony, wrong `labelStyle` prop signature.

What is prop signature ?

**Comment by ali-mozaffari** [comment]
Hi @goupilAnthony, wrong labelStyle prop signature.
What a foolish answer!
