### ISSUE TITLE
Label font color not changing

### ISSUE THREAD

**Issue by mcctrix** [toomuchdesign/react-minimal-pie-chart#244]
### Do you want to request a _feature_ or report a _bug_?

...
reporting a bug
### What is the current behaviour?
color and backgroundColor property not working to change label color in piechart
i have tried fontColor as shown in a article https://medium.com/@tgknapp11/render-a-chart-with-react-minimal-pie-chart-e30420c9276c but still no luck
...

### What is the expected behaviour?
it suppose to change label color 
...

### Steps to Reproduce the Problem

1. ... labelStyle={{fontColor: ""white}}
2. ...
3. ...

### Specifications

- Version:
- Platform:
- Subsystem:

**Comment by toomuchdesign** [comment]
'labelStyle' must return a set of [SVG attributes](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute).
