### ISSUE TITLE
Segment Border

### ISSUE THREAD

**Issue by alik90788** [toomuchdesign/react-minimal-pie-chart#245]
### Do you want to request a _feature_ or report a _bug_?
I want to ask can we give custom border radius to the segments instead of using rounded property also segmentsStyle is not working.
...

### What is the current behaviour?
Currently the style is not being applied from the segments style
...

### What is the expected behaviour?

...

### Steps to Reproduce the Problem

1. ...
2. ...
3. ...

### Specifications

- Version:
- Platform:
- Subsystem:

**Comment by toomuchdesign** [comment]
Border radius is a CSS prop that SVG doesn't support.
https://css-tricks.com/svg-properties-and-css/#aa-properties-shared-between-css-and-svg
