### ISSUE TITLE
Are there any ways to set the same distance/padding between slices

### ISSUE THREAD

**Issue by haodev007** [toomuchdesign/react-minimal-pie-chart#250]
Hi,
I have recently used this library and it is very great. thanks for your amazing work!
Can we adjust distance between slices as the same?
Attached refer img, here.
![image](https://user-images.githubusercontent.com/98631674/193146678-7c9416df-2c21-4167-89f0-c962a3bffa60.png)
i.e. padding of center side is smaller than outside one and inside is the smallest. Can I set the same space?
Thanks in advance!

**Comment by toomuchdesign** [comment]
HI @haodev007,
thanks for writing. It's a known limitation since this library renders chart slices as simple circumference segments paths with a given stroke width instead of drawing the 4 slice borders.

I can't see any workaround. Happy to discuss possible solutions which I can't see right now.
