### ISSUE TITLE
PieChart component rendering error ExceptionsManager Error: Text strings must be rendered within a <Text> component.

### ISSUE THREAD

**Issue by banghia112** [toomuchdesign/react-minimal-pie-chart#259]
### Do you want to request a _feature_ or report a _bug_?

i was just trying out a simple usage and i got this error

### What is the current behaviour?

receiving Error: Text strings must be rendered within a <Text> component.

### What is the expected behaviour?

component rendering as normal

### Steps to Reproduce the Problem

![image](https://user-images.githubusercontent.com/89189266/209745068-e103245a-7092-4d7f-ac5c-bd2fe066e5be.png)

### Specifications

- Version: "react-minimal-pie-chart": "^8.4.0",
- Platform: react native
- Subsystem:
System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1
    Memory: 81.38 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.0.1 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.19.3 - ~/Documents/Med247/med247-app/node_modules/.bin/npm
    Watchman: 2022.11.07.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/admin/.rvm/gems/ruby-2.7.4/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/bin/javac
    Python: 3.8.6 - /Users/admin/.pyenv/shims/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by toomuchdesign** [comment]
Hi @banghia112, `react-native` is unfortunately not supported.
