### ISSUE TITLE
paddingAngle wrong

### ISSUE THREAD

**Issue by brightsider** [toomuchdesign/react-minimal-pie-chart#36]
Used paddingAngle 20
![chart](https://user-images.githubusercontent.com/4996231/54909808-ad1eb100-4ef3-11e9-8177-a92134515593.png)

**Comment by toomuchdesign** [comment]
Hi @brightsider!
Yep, currently padding implementation has some limitation. The works for v4 are open, I'll try to handle this issue there, also. 👍

**Comment by toomuchdesign** [comment]
Fixed by #37. We'll be released (pretty soon) with v4.
