### ISSUE TITLE
It seems there is not a way to get the title to show up in the pie, just the percentage

### ISSUE THREAD

**Issue by pkellner** [toomuchdesign/react-minimal-pie-chart#38]
I looked thru source and don't see an option for this.

**Comment by toomuchdesign** [comment]
When you provide a function as `label` property, the **return value** will be rendered as **label's content**.

The function receives the **"extended `data`" object** and the `index` of the data entry corresponding to the label to be rendered.

This should work for in your case:

```js
label={({ data, dataIndex }) => data[dataIndex].title}
```

**Comment by toomuchdesign** [comment]
v4 docs updated.
Feel free to re-open in case the issue is still not solved.

**Comment by pkellner** [comment]
thanks
