### ISSUE TITLE
not able to add custom classNames to define color by variable

### ISSUE THREAD

**Issue by sahanaravi** [toomuchdesign/react-minimal-pie-chart#43]
### Do you want to request a _feature_ or report a _bug_?

...not able to add custom classNames to define color by variable

### What is the current behaviour?

...data={[{
              title: 'One',
              value: 82,
              color: '#007DCD'
            }]}

### What is the expected behaviour?

...data={[{
              title: 'One',
              value: 82,
              color: {theme.palette.secondary.main}
            }]}

**Comment by toomuchdesign** [comment]
Hi @sahanaravi,
`color` property is forwarded as [`stroke` attribute](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke) of the `path` element representing a chart's slice. A class name is a simple string and can't be interpreted as a color.
