### ISSUE TITLE
Typescript error: Generic type 'ReactElement<P>' requires 1 type argument(s)

### ISSUE THREAD

**Issue by B-Reif** [toomuchdesign/react-minimal-pie-chart#45]
### Do you want to request a _feature_ or report a _bug_?

Bug

### What is the current behaviour?

When building in a typescript environment, Typescript throws an error:
```
/my-project/node_modules/react-minimal-pie-chart/src/types/index.d.ts
Type error: Generic type 'ReactElement<P>' requires 1 type argument(s).  TS2314

    35 | declare type LabelPropAsFunction = (
    36 |   labelProps: LabelProps
  > 37 | ) => number | string | React.ReactElement;
       |                        ^
    38 |
    39 | declare type EventHandler = (
    40 |   event: React.MouseEvent,
```

### What is the expected behaviour?
I expect Typescript to compile the library successfully.

### Steps to Reproduce the Problem

Attempt to compile the library in a Typescript environment with React at `^16.8.4`.

**Comment by toomuchdesign** [comment]
It might be an issue with `@types/react`. May you make sure it's not related with [this issue](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/33065)?
