### ISSUE TITLE
[Question] Is there a way to trigger animation when chart comes into view?

### ISSUE THREAD

**Issue by willstocks-tech** [toomuchdesign/react-minimal-pie-chart#46]
### Do you want to request a _feature_ or report a _bug_?

A question

### What is the current behaviour?

When animating a chart, is there a way to have the animation only run when the chart is scrolled into view, not just straight away on page load? If it's out of viewport, you miss the animation.

### What is the expected behaviour?

Some way to "delay" the animation until the chart is in view?

### Steps to Reproduce the Problem

1. I added a pie chart (donut) to my site, towards the bottom of the page, using the following code:

```
<div className="chart php">
    <PieChart
        data={[{
	    value: 65,
	    color: '#E38627'
	}]}
	totalValue={100}
	lineWidth={20}
	label
	labelStyle={{
	    fontSize: '25px',
	    fontFamily: 'sans-serif'
	}}
	labelPosition={0}
	rounded
	animate
    />
    <h3>PHP</h3>
</div>
```

2. Load the page, scroll down and the chart is already sat there happily
3. Load the page pre-scrolled down and the chart animates on load?

### Specifications

- Version:
- Platform:
- Subsystem:

**Comment by toomuchdesign** [comment]
Hi @willstocks-tech,
in regard to manually trigger the animation you might use the `reveal` property. Render the chart with `reveal` set to `0` and then set it to `100` when you're ready to go.

As for detecting component visibility It's out of the scope of this library. I'd suggest to wrap the chart with a special utility component designed for that.

**Comment by willstocks-tech** [comment]
Thanks @toomuchdesign - I think I have managed to work this one out now 😄 

I'm using `react-intersection-observer` ([link](https://github.com/thebuilder/react-intersection-observer)) which is pretty lightweight and appears to do the job for me!

If anyone is interested:

```js
import { InView } from 'react-intersection-observer'

function Home() {
  return (
    /* other stuff going on here, but excluded for simplicities sake*/
    <InView>
      {({ inView, ref }) => (
        <div ref={
          <Pies
            inview={inView}
          />
        </div>
      )}
    </InView>
  );
}
```

which passes through to my "pies.js":

```js
import PieChart from 'react-minimal-pie-chart';

function Pies(props) {	
  let pierender = props.inview ? 100 : 0;
  return (
    /* Again, other stuff here but omitted */
    <PieChart
      data={[{
        value: 80,
        color: '#E38627'
      }]}
      totalValue={100}
      lineWidth={20}
      label
      labelStyle={{
        fontSize: '25px',
        fontFamily: 'sans-serif'
      }}
      labelPosition={0}
      rounded
      animate
      reveal={pierender}
    />
  );
}
```
