### ISSUE TITLE
Doughnut chart

### ISSUE THREAD

**Issue by NetJS** [toomuchdesign/react-minimal-pie-chart#49]
![chart](https://user-images.githubusercontent.com/6763285/59030751-81606580-886a-11e9-8abd-9518fb764357.png)

Hi, thanks for your library :)
I wanna create chart like on image above

blue progress should always start from 12 oclock
other part of chart should be filled with silver

is it possible?

I tried a bit with code below, but its not what I need
```
    <ReactMinimalPieChart
            className="chart-shadow"
            data={[
              {
                title: 'Your progress',
                value: 10,
                color: '#40d3e3'
              }
            ]}
            lineWidth={40}
            rounded
            animate
            totalValue={100}
            lengthAngle={-360}
       />
```

**Comment by toomuchdesign** [comment]
Hi @NetJS,
`react-minimal-pie-chart` provides out of the box what you need except for the grey background segment.

Background segment is actually in the Readme's todo's, but I've never found a good reason for actually implementing it. PR's are welcome :).

BTW you can pretty easily implement the background segment on your application drawing a CSS or svg ring below the chart.

**Comment by NetJS** [comment]
> Hi @NetJS,
> `react-minimal-pie-chart` provides out of the box what you need except for the grey background segment.
> 
> Background segment is actually in the Readme's todo's, but I've never found a good reason for actually implementing it. PR's are welcome :).
> 
> BTW you can pretty easily implement the background segment on your application drawing a CSS or svg ring below the chart.

Thanks! what about start always from 12 oclock? because now its starts always different (depends of value) , for example if value: 10 || 25 || 50 || 75

**Comment by toomuchdesign** [comment]
If you need to animate a single element you might consider using and updating the `reveal` property. See [demo](https://github.com/toomuchdesign/react-minimal-pie-chart/blob/master/stories/LoadingIndicatorStory.js).

In your  case `startAngle` and `totalValue` should do with their default values.

**Comment by toomuchdesign** [comment]
v4.2.0 ships with a new `background` property. Your case should be covered by [this example](https://github.com/toomuchdesign/react-minimal-pie-chart/blob/ddbe59bac791ed75d157817a9b4a4ed5ec7a512d/stories/PartialLoadingIndicatorStory.js#L23).

Cheers!

**Comment by NetJS** [comment]
Hello :) Will try, thanks!
