### ISSUE TITLE
add support for text values?

### ISSUE THREAD

**Issue by EdsonAlcala** [toomuchdesign/react-minimal-pie-chart#5]
For instance, in a pie chart 

<img width="433" alt="screen shot 2017-12-15 at 00 07 31" src="https://user-images.githubusercontent.com/3077635/34020420-07ea4590-e12c-11e7-89e8-c0459d8e7ea1.png">

**Comment by toomuchdesign** [comment]
Hi @EdsonAlcala, I created this library as an attempt to provide basic and flexible pie charts with minimal performance and weight impact.

I'd really like to introduce this feature, but I don't see how to do it without changing the original aim of the project. Suggestions are welcome, of course.

BTW, for fully-featured charting I'd suggest you to give [recharts](https://github.com/recharts/recharts) a try. It's an awesome piece of code.

**Comment by fabiodev2grow** [comment]
This would actually be a really cool new feature!

I'm trying to create something like this:
![image](https://user-images.githubusercontent.com/24845513/36686123-40a16e2e-1b1d-11e8-951f-73621ae33c31.png)

(Recharts is not working for me sadly and your project is doing wonders! Now text/label/tooltip would be a much needed feature!)

**Comment by toomuchdesign** [comment]
Labels shipped with [v3.5.0](https://github.com/toomuchdesign/react-minimal-pie-chart/releases/tag/v3.5.0).
