### ISSUE TITLE
IE syntax error

### ISSUE THREAD

**Issue by luca-esse** [toomuchdesign/react-minimal-pie-chart#50]
### Do you want to request a _feature_ or report a _bug_?

Bug

### What is the current behaviour?

Importing react-minimal-pie-chart causes a syntax error on IE 11

### Steps to Reproduce the Problem

The problem is reproducible even in the [storybook](https://toomuchdesign.github.io/react-minimal-pie-chart/index.html?path=/story/pie-chart--default) with IE 11 

### Specifications

- Version: 4.1.0, 4.0.0
- Platform: IE 11

**Comment by toomuchdesign** [comment]
Hi @luca-esse,
Would you please provide more info about the error?

**Comment by luca-esse** [comment]
This is a screenshot of the storybook, I'm experiencing the same behavior on my application with IE 11 and react-minimal-pie-chart 4.1.0/4.0.0;
![Storybook](https://user-images.githubusercontent.com/16616566/59093327-f50a7d00-8913-11e9-9b1b-a5a5bb5a6c25.PNG)

My application:
![My application](https://user-images.githubusercontent.com/16616566/59093730-ed97a380-8914-11e9-8ff8-865a8df40ea7.PNG)

Downgrading to react-minimal-pie-chart 3.5.0 solves the problem.

**Comment by toomuchdesign** [comment]
Thanks. It seems related to `@babel/env` default browsers config.

**Comment by toomuchdesign** [comment]
Hi @luca-esse,
this should be addressed by v4.1.1.
Let me know if the patch fixes the problem and -if yes- please close the issue.

Salutami la bella Torino. :)
Ciao!

**Comment by luca-esse** [comment]
Hi @toomuchdesign,
Yes, it did, I can confirm it's working now.

Grazie! Te la saluto con piacere :)
