### ISSUE TITLE
`reveal` draws segment in the wrong direction

### ISSUE THREAD

**Issue by toomuchdesign** [toomuchdesign/react-minimal-pie-chart#53]
### Do you want to request a _feature_ or report a _bug_?

Bug

### What is the current behaviour?

`reveal` prop doesn't reveal segments in the same direction as the segment itself is drawn.

In [this example](http://localhost:9001/?path=/story/loading-indicator--with-reveal) segments are drawn counterclockwise while reveal works clockwise.

### What is the expected behaviour?

`reveal` should respect segment drawing direction.

**Comment by GalEldarDev** [comment]
Any updates on this issue? Can we merge the PR?

**Comment by toomuchdesign** [comment]
I'll release a major this weekend.
Cheers!

**Comment by toomuchdesign** [comment]
Shipped with #69
