### ISSUE TITLE
IE support

### ISSUE THREAD

**Issue by edwardfhsiao** [toomuchdesign/react-minimal-pie-chart#6]
I suggest that modify your "animate Description" markdown to "Animate sectors on component mount(IE9 would not work properly if set to true)"  kind of instruction, which could save a lot of times for people that searching for IE support.

**Comment by toomuchdesign** [comment]
Hi @edwardfhsiao, thanks for the report.
Does it actually break on IE9 or just doesn't animate. Do you get any error message in the console?

BTW I'll test it ASAP.
Cheers.

**Comment by edwardfhsiao** [comment]
No, there is no error. The problem is it won't render correctly, the initialized svg path is different since it does not work.
chrome: 
![image](https://user-images.githubusercontent.com/11728228/35510558-81b829d4-0533-11e8-9df3-60a0d94a5363.png)
&lt;path d="M 93.75 50 A 43.75 43.75 0 1 1 85.20706370475699 24.028377692389284" stroke-width="12.5" stroke-dasharray="247.083127692548" stroke-dashoffset="494.16625538509595" stroke="#5297ff" fill="none" style="transition: stroke-dashoffset 500ms ease-out;"&gt;&lt;/path&gt;

IE11:
![image](https://user-images.githubusercontent.com/11728228/35510622-c9b955dc-0533-11e8-9c90-1a112678b30e.png)
&lt;svg xmlns="http://www.w3.org/2000/svg" style="display: block;" viewBox="0 0 100 100" width="100%" height="100%"&gt;&lt;path style="transition:stroke-dashoffset 500ms ease-out;" fill="none" stroke="#5297ff" stroke-dasharray="274.889" stroke-dashoffset="549.779" stroke-width="12.5" d="M 93.75 50 A 43.75 43.75 0 1 1 93.75 49.9992" /&gt;&lt;/svg&gt;

IE9:
![image](https://user-images.githubusercontent.com/11728228/35510670-fcdfc748-0533-11e8-96e3-5d8de782c483.png)
&lt;svg xmlns="http://www.w3.org/2000/svg" style="display: block;" viewBox="0 0 100 100" width="100%" height="100%"&gt;&lt;path fill="none" stroke="#5297ff" stroke-dasharray="274.889" stroke-dashoffset="549.779" stroke-width="12.5" d="M 93.75 50 A 43.75 43.75 0 1 1 93.75 49.9992" /&gt;&lt;/svg&gt;

the paths are different

**Comment by toomuchdesign** [comment]
Thanks @edwardfhsiao, now it's clear.
IE renders SVG path in its own way! I can't think of a solution right now. BTW PR/suggestion are welcome.

If no solution is found, I'll sadly update the docs to warn about this issue.

Greetings!

**Comment by toomuchdesign** [comment]
Browsers support section added to docs. Thanks!

**Comment by erezcohen** [comment]
Hi, this seems like a cool chart lib. Thanks.
The issue of IE11 support is not clear.
Is it just animation that does not work?

BTW is there a live example I can try on IE?
I tried the demo on a VM but it seems like storybook itself doesn't render there..

**Comment by toomuchdesign** [comment]
Hi @erezcohen,
Animations in IE11 are supposed to work but, If I'm not mistaken, they effect the visual output when the Chart is rendered as full Pie.

I'd like Storybook to work with ie11 but it seems to have lately provided [intermittent support](https://github.com/storybookjs/storybook/issues/4099) to it.

I've just updated Storybook to the last available version which is now supposed to work. Would mind giving it a try now?

Greetings!

**Comment by erezcohen** [comment]
I've just tried the demo page again and it didn't work asnwell (at least not from my Win7 vm).

Regardless, I have just added this package to my product.
It was awesomely easy to add a donut chart, but on  IE11 it was positioned wrongly: it has dropped down below the desired div.

After a bit of struggle I was able to fix it by forcing width and height to the div wrapping the svg added by the chart like so:
```
> div {
      height: 100%;
      width: 100%;
    }
```
I would recommend adding it to all envs (or dropping the div altogether) but it might be just related to specific settings in my app.
Alas I cannot share a reproducible example but perhaps you'd be able to set up a simple example on jsfiddle and I'll look at it with IE? I tried this earlier using the UMD link but ran into all sorts of errors so maybe you'll do a better job at that.

**Comment by toomuchdesign** [comment]
I couldn't reproduce on virtual machine.

Actually If found that IE is **not able** to let the chart SVG element's **width adapt to its `div` container**. So it basically needs the component to declare a fixed height like:

```js
<PieChart
  style={{
    height: '300px'
  }}
/>;
```
Since it's a well known IE issue, it's nothing I would address here.
