### ISSUE TITLE
Labels not centered in Firefox

### ISSUE THREAD

**Issue by janhartmann** [toomuchdesign/react-minimal-pie-chart#67]
### Do you want to request a _feature_ or report a _bug_?
A bug
...

### What is the current behaviour?
Using single label is not centered
...
![image](https://user-images.githubusercontent.com/1107383/60807030-e4ecf400-a184-11e9-9b75-038fa3e0c56c.png)

### What is the expected behaviour?
Using single label is centered
...

### Steps to Reproduce the Problem

1. Open Firefox
2. Go to https://toomuchdesign.github.io/react-minimal-pie-chart/index.html?path=/story/labels--single-label

### Specifications

- Version: 4.2.0
- Platform: MacOS / Windwos
- Subsystem:

**Comment by toomuchdesign** [comment]
Hi @janhartmann,
[it seems](https://stackoverflow.com/questions/19212498/firefox-support-for-alignment-baseline-property) that firefox doesn't play well with `alignment-baseline` property when applied to `<text>` elements.

Applying `dominant-baseline: middle` might solve the issue. I'll open PR asap unless you'd like to take care of it.

Cheers and thanks!

**Comment by janhartmann** [comment]
No problem and thanks for this great library :-)

**Comment by toomuchdesign** [comment]
You're welcome! :)

**Comment by toomuchdesign** [comment]
Addressed in #68 even though `dominant-baseline` is not widely supported.
