### ISSUE TITLE
Text strings must be rendered within a <Text> component.

### ISSUE THREAD

**Issue by isohanvanani** [toomuchdesign/react-minimal-pie-chart#79]
I am new to react-native.
While implementing pie chart I used react-minimal-pie-chart and got error:
`Invariant Violation:  Text strings must be rendered within a <Text> component.`
For reference see attached screenshot. 

![Screenshot 2019-09-19 at 6 30 20 PM](https://user-images.githubusercontent.com/43265432/65246301-e1be9e80-db0b-11e9-8837-2f6fea79bf07.png)

**Comment by toomuchdesign** [comment]
This library currently targets only browsers. See #20.
I'm open to proposals on how to support native targets.
