### ISSUE TITLE
cancel all subscriptions and asynchronous tasks in the componentWillUnmount method

### ISSUE THREAD

**Issue by edwardfhsiao** [toomuchdesign/react-minimal-pie-chart#8]
I've encountered this problem

![image](https://user-images.githubusercontent.com/11728228/39281493-804ddb64-4937-11e8-8bd5-84f5c088cede.png)

Warning: Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in ReactMinimalPieChart (created by Index)
    in div (created by Index)
    in div (created by Index)
    in div (created by Index)
    in div (created by Index)
    in div (created by Index)
    in div (created by Index)
    in div (created by Index)
    in div (created by Index)
    in div (created by Index)
    in Index (created by Connect(Index))
    in Connect(Index) (created by AsyncRoute)
    in AsyncRoute (created by Route)

Not sure if is the component issue. If it is, maybe you can cancel the asynchronous tasks in the componentWillUnmount?

Thx

**Comment by toomuchdesign** [comment]
Hi @edwardfhsiao!
Good catch. I'm quite sure it comes from the component. All the evidences point to the starting animation, which is triggered asynchronously in componentDidMount hook. I'm on it, I'll release a patch, soon.

Thank you. Cheers!

**Comment by toomuchdesign** [comment]
Hi @edwardfhsiao!
What do you think about [this PR](https://github.com/toomuchdesign/react-minimal-pie-chart/pull/9)?

Could it fix the issue?
Cheers!

**Comment by edwardfhsiao** [comment]
yes I think so

**Comment by toomuchdesign** [comment]
Fixed by #9.
