### ISSUE TITLE
label block onClick

### ISSUE THREAD

**Issue by Nichon4** [toomuchdesign/react-minimal-pie-chart#81]
### Do you want to request a _feature_ or report a _bug_?

_bug_

### What is the current behaviour?

when label and onClick props are used, clicks on label do nothing

### What is the expected behaviour?

onClick function call

### Steps to Reproduce the Problem

1. Create PieChart with label and onClick props
2. click
3. ...

### Specifications

- Version: 5.0.1
- Platform: Google Chrome 77.0.3865.90
- Subsystem: Windows10

**Comment by toomuchdesign** [comment]
Hi @Nichon4, thanks for reporting!

I see at least 2 possible solutions:
- assign labels a CSS `pointer-events: none` property
- re-assign labels the interaction callbacks

I'd currently be inclined for the 2nd one.

**Comment by toomuchdesign** [comment]
Quick update:
I considered the options available to work around this issue and I changed my mind.

The most effective **solution** seems to be using the `labelStyle` property to assign a  [CSS `pointer-events: none` property](https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events) to each label and make them non interactive:

```jsx
<PieChart
  label={true}
  labelStyle={{
    pointerEvents: 'none',
  }}
/>
```
Re-assigning event listeners to the labels would work for `click` events but would trigger the events repeatedly while hovering in-between segments and labels.

@Nichon4 please close the issue if the solution provided works for you.
Cheers!

**Comment by Nichon4** [comment]
@toomuchdesign your solution is work.
Thanks a lot!
